CREATE TABLE SPECIAL_OFFER (
  ID            INTEGER PRIMARY KEY,
  SPECIAL_PRICE DOUBLE NOT NULL,
  ITEMS_AMOUNT  INTEGER NOT NULL
);

CREATE TABLE PRODUCT (
  ID       INTEGER PRIMARY KEY,
  CODE     VARCHAR2(100 CHAR) NOT NULL,
  NAME     VARCHAR2(255 CHAR) NOT NULL,
  PRICE    DOUBLE NOT NULL,
  SPECIAL_OFFER_ID INTEGER
);

ALTER TABLE PRODUCT ADD FOREIGN KEY (SPECIAL_OFFER_ID) REFERENCES SPECIAL_OFFER(ID);

