INSERT INTO OFFER VALUES (1, 70, 3);
INSERT INTO OFFER VALUES (2, 15, 2);

INSERT INTO PRODUCT VALUES (1, 'A', 'Product A', 40, 1);
INSERT INTO PRODUCT VALUES (2, 'B', 'Product B', 10, 2);
INSERT INTO PRODUCT VALUES (3, 'C', 'Product C', 30, null);
INSERT INTO PRODUCT VALUES (4, 'D', 'Product D', 25, null);